builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
      - "rentberry/mandrill-prometheus-exporter:latest"
      - "rentberry/mandrill-prometheus-exporter:{{ .Tag }}"
    skip_push: auto
    dockerfile: Dockerfile
